eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservice:
  HelloWorldService:
    endpoints:
      endpoint:
        uri: http://HELLOWORLDSERVICE/free/sayHello
  LambdaHelloWordService:
    endpoints:
      endpoint:
        uri: http://LAMBDAHELLOWORLDSERVICE/secured/sayHello
#   AuthServer:
#     endpoints:
#       endpoint:
#         uri: http://AUTHSERVER/oauth/token
  AuthServer:
    endpoints:
      endpoint:
        uri: http://RESOURCESERVER/oauth/token, /oauth/check_token , /v1/utilities
